version: '3'
services:
  dh_server:
    container_name: server
    restart: always
    build:
      context: ./
      dockerfile: server/Dockerfile
    ports:
      - 3000:3000
    command: "pm2-runtime src/index.js"

  # mongodb:
  #   image: mongo:5.0
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=datahouse
  #     - MONGO_INITDB_ROOT_PASSWORD=datahouse
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - mongodb_data_container:/data/db
  
  dh_client:
    container_name: client
    restart: always
    build:
      context: ./
      dockerfile: client/Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - dh_server