module.exports = {
  HOST: '127.0.0.1',
  PORT: 27017,
  DB: 'datahouse',
  DB_TEST: 'datahouse_test',
  CONNECTIONOPTIONS: {
    useCreateIndex: true,
    useNewUrlParser: true,
    useUnifiedTopology: true,
    useFindAndModify: false,
  },
  initalMenus: [{
    auth: ['/demands'],
    parentPath: '',
    path: '/demands',
    name: '需求系统',
    icon: '',
  }, {
    auth: ['/tables'],
    parentPath: '',
    path: '/tables',
    name: '报表系统',
    icon: '',
  }, {
    auth: ['sysconfigs'],
    parentPath: '',
    path: '/sysconfigs',
    name: '全局配置',
    icon: '',
  }, {
    auth: [
      'GetMenus',
      'GetMenu',
      'AddNewMenu',
      'DeleteMenu',
      'UpdateMenu',
    ],
    parentPath: '/sysconfigs',
    path: '/sysconfigs/menuslist',
    name: '菜单列表',
    icon: 'OrderedListOutlined',
  }, {
    auth: [
      'GetConfigs',
      'GetConfig',
      'AddNewConfig',
      'DeleteConfig',
      'UpdateConfig',
      'AddNewFilter',
      'UpdateFilter',
    ],
    parentPath: '/tables',
    path: '/tables/configs/list',
    name: '配置中心',
    icon: 'SettingFilled',
  }, {
    auth: [
      'GetDemands',
      'GetDemand',
      'AddNewDemand',
      'DeleteDemand',
      'UpdateDemand',
    ],
    parentPath: '/demands',
    path: '/demands/list',
    name: '需求列表',
    icon: 'BulbOutlined',
  }, {
    auth: [
      'GetUsers',
      'DeleteUser',
      'UpdateUser',
    ],
    parentPath: '/sysconfigs',
    path: '/sysconfigs/userslist',
    name: '用户列表',
    icon: 'UserOutlined',
  }, {
    auth: [
      'GetTableData',
      'ExportTableData',
    ],
    parentPath: '/tables',
    path: '/tables/databoard/:id',
    name: '仪表盘',
    icon: 'PieChartOutlined',
  }],
};
